apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # livenessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - non-existent-file
        #   initialDelaySeconds: 5
        #   periodSeconds: 180
