apiVersion: ephemeral-access.argoproj-labs.io/v1alpha1
kind: AccessRequest
metadata:
  name: leoluz-devops-2j2kr
  namespace: argocd
spec:
  application:
    name: ephemeral
    namespace: argocd
  duration: 1m0s
  role:
    friendlyName: Devops (Write)
    ordinal: 1
    templateName: devops
  subject:
    username: leoluz
