apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
data:
  # leoluz password is "12345678" < this is just used for local tests!!! :P
  accounts.leoluz.password: JDJhJDEwJElLSzJjV1V3L1pMNFpmejJsLnMwYmVwOUhGOXYzeU1VVlljUU1GMjR4MmxNQ1VxeG5Ua1hD
  accounts.leoluz.passwordMtime: MjAyNS0wNi0wM1QyMTowMTo1NFo=
