apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  accounts.leoluz: login,apiKey
  extension.config.ephemeral: |-
    services:
    - url: http://localhost:8888
