apiVersion: ephemeral-access.argoproj-labs.io/v1alpha1
kind: RoleTemplate
metadata:
  name: devops
spec:
  name: devops
  description: write permission in application {{.application}}
  policies:
    - p, {{.role}}, applications, sync, {{.project}}/{{.application}}, allow
    - p, {{.role}}, applications, action/*, {{.project}}/{{.application}}, allow
    - p, {{.role}}, applications, delete/*/Pod/*, {{.project}}/{{.application}}, allow
    - p, {{.role}}, logs, get, {{.project}}/{{.namespace}}/{{.application}}, allow
