apiVersion: v1
kind: Pod
metadata:
  name: argo-cd-tools
  annotations:
    iam.amazonaws.com/role: k8s-dev-argocd-usw2-test
spec:
  containers:
  - command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    image: docker.intuit.com/dev/deploy/argo-cd-tools/service/argo-cd-tools:0.0.9
    imagePullPolicy: Always
    name: kubectl
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 256Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
